# Generated by Django 4.2.7 on 2023-12-24 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_rename_preview_image_product_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Номер версии')),
                ('title', models.CharField(blank=True, max_length=30, null=True, verbose_name='Название версии')),
                ('is_actual', models.BooleanField(default=False, verbose_name='Признак текущей версии')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Версию',
                'verbose_name_plural': 'Версии',
                'ordering': ['number'],
            },
        ),
    ]
